server:
  port: 0
#spring:
#  application:
#    name: book
eureka:
  client:
    registryFetchIntervalSeconds: 1
    instanceInfoReplicationIntervalSeconds: 1
    initialInstanceInfoReplicationIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://172.31.35.136:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
#    preferIpAddress: true
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
